---
title: "Stats"
author: "Julia Prein"
date: "12/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse) # data handling etc.
library(viridis) # col scales, plotting...
library(ggpubr)
library(ggridges)
library(ggthemes)
library(tidyboot) # for bootstrap CIs
library(brms) # modeling
library(splithalfr) # reliability 
library(tidybayes) # for stat_halfeye
library(ggdist)
library(parallel) # for mclapply in splithalf reli

options(scipen = 999)
theme_set(theme_classic())
```

```{r load_data}
testtrials <- readRDS(file = "../data/tango-testtrials.rds") %>% 
  # determine order of factors
  mutate(
    targetPosition = factor(targetPosition, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "box1", "box2", "box3", "box4", "box5")), 
    studyversion = factor(studyversion, levels = c("hedge", "box")), 
    datacollection = factor(datacollection, levels = c("in-person - supervised", "remote - unsupervised")),
    sample = factor(sample, levels = c("kids", "adults")), 
    studytype = factor(studytype, levels = c("vali", "vali2", "reli")),
    
    # for models, summarize targetPositions in a way that it's symmetrical for left/ right side
    # the smaller the value, the more central the position
    symmetricPosition = ifelse(studyversion == "box", 
                               # for box version
                               case_when(
                                  targetPosition == "box3" ~ 0, 
                                  targetPosition == "box2" | targetPosition == "box4" ~ 1,
                                  targetPosition == "box1" | targetPosition == "box5" ~ 2), 
                               # for hedge version
                               targetCentralityX
                       ), 
    
    # distance between target and click in balloon widths (balloon width is 160 SVG units)
    clickDistInBalloons = abs(clickDistFromTargetCenterX)/160,
  )
```

# VARIATION

```{r vali_data}
inddiff <- testtrials %>% 
  filter(studytype == "vali" & (ageInYears < 6 | ageInYears == 18)) %>% 
  mutate(ageInYears = factor(ageInYears, levels = c("3", "4", "5", "18")))
```

```{r variation_hedge_preparateData}
variationHedgeInd <- inddiff %>% 
  filter(studyversion == "hedge") %>% 
  mutate(
    ageInYearsExact = ifelse(sample == "kids", ageInMonths/12, 18), 
    ageInMonthsCentered = scale(ageInYearsExact, center = TRUE, scale = TRUE)[,1],
  ) %>% 
  group_by(sample, datacollection, ageInYears, ageInYearsExact, ageInMonthsCentered, subjID) %>%
  summarise(mean = mean(clickDistInBalloons, na.rm = TRUE))

variationHedge <- variationHedgeInd %>%
  group_by(sample, datacollection, ageInYears) %>%
  tidyboot_mean(column = mean)
```

```{r age_hedge_model}
mDataAgeHedge <- inddiff %>% 
  filter(studyversion == "hedge" & sample == "kids") %>% 
  mutate(
    # scaled (centered around mean, SD = 1, i.e., z-transformed)
    age = scale(ageInMonths), 
    symmetricPosition = scale(symmetricPosition),
    trialNr = trialNr - min(trialNr), 
  ) %>% 
  select(subjID, age, ageInMonths, datacollection, symmetricPosition, trialNr, clickDistInBalloons)

mAgeHedge <- brm(clickDistInBalloons ~ age + datacollection + symmetricPosition + trialNr + (1 + symmetricPosition + trialNr | subjID),
                    data = mDataAgeHedge,
                    family = lognormal(),
                    warmup = 1000, 
                    iter   = 3000, 
                    chains = 4, 
                    inits  = "random",
                    cores  = 4)

write.csv(mAgeHedge, "../saves/mAgeHedge.csv", quote = F, row.names = F)
saveRDS(mAgeHedge, "../saves/mAgeHedge.rds")

# pp_check(mAgeHedge) + xlim(0, 10)
```

```{r GLMM_plot_hedge}
nd_hedge <- mDataAgeHedge %>% 
  select(-c(clickDistInBalloons, trialNr)) %>% 
  mutate(trialNr = 0, symmetricPosition = 0)

pred_hedge <- fitted(mAgeHedge, newdata = nd_hedge, re_formula = NA) %>% as_tibble() %>% bind_cols(nd_hedge) 

hedge_variation_plot_GLMM <- ggplot() +
  
  # use model predictions for smoother
  geom_smooth(
    data = pred_hedge, 
    aes(x = ageInMonths/12, y = Estimate, ymin = Q2.5, ymax = Q97.5, group = datacollection, lty = datacollection), 
    stat = "identity", size = 0.5, alpha = 0.15, col = "darkgrey",
  ) +
  
  geom_point(
    data = variationHedgeInd %>% filter(sample == "kids"), 
    aes(x = ageInYearsExact, y = mean, col = ageInYears, shape = datacollection, alpha = datacollection)
  ) +
  
  geom_pointrange(
    data = variationHedge %>% filter(sample == "kids"), 
    aes(x = as.numeric(as.character(ageInYears))+.5, y = mean, ymin = ci_lower, ymax = ci_upper, col = ageInYears, shape = datacollection, alpha = datacollection), size = 0.8, position=position_dodge(width = 0.1)
  ) +
  
  scale_shape_manual(values = c(16, 18)) + 
  scale_alpha_discrete(range = c(1, 0.4)) + 
  scale_linetype_manual(values = c("solid", "dashed")) + 
  
  # adult data
  geom_jitter(
    data = variationHedgeInd %>% filter(sample == "adults"), 
    aes(x = 6.5, y = mean, col = ageInYears, shape = datacollection), alpha = 0.5, width = .05, height = .01,  
  ) +

  geom_pointrange(
    data = variationHedge %>% filter(sample == "adults"), 
    aes(x = 6.5, y = mean, ymin = ci_lower, ymax = ci_upper, shape = datacollection), 
    size = 0.8,
  ) +
  
  labs(x = "Age in years", y = "Average imprecision in target width", col = "Age group", shape = "Data collection mode", alpha = "Data collection mode", lty = "Data collection mode") + 
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d", "darkgrey"), breaks = c("3", "4", "5", "18"), labels = c("3-year-olds", "4-year-olds", "5-year-olds", "Adults")) +
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 1)) + 
  scale_x_continuous(breaks = seq(3, 6.5, 0.5), labels = c("3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "Adults")) + 

  theme(legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"), 
        legend.direction = "vertical", 
        legend.box = "horizontal",
        legend.position = c(0.72, 0.85), 
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")
        )

hedge_variation_plot_GLMM
saveRDS(hedge_variation_plot_GLMM, file = "../saves/tango-hedge-variation-plot-GLMM.rds")
# ggsave("../figures/tango_hedge_variation_GLMM.png", width = 7, height = 4)
```

```{r variation_box_prepareData}
variationBoxInd <- inddiff %>% 
  filter(studyversion == "box") %>% 
  mutate(
    ageInYearsExact = ifelse(sample == "kids", ageInMonths/12, 18), 
    ageInMonthsCentered = scale(ageInYearsExact, center = TRUE, scale = TRUE)[,1],
  ) %>% 
  group_by(sample, datacollection, ageInYears, ageInYearsExact, ageInMonthsCentered, subjID) %>% 
  summarise(mean = mean(correctBox, na.rm = TRUE))

variationBox <- variationBoxInd %>%
  group_by(sample, datacollection, ageInYears) %>%
  tidyboot_mean(column = mean)
```

```{r age_box_model}
# define data
mDataAgeBox <- inddiff %>% 
  filter(studyversion == "box" & sample == "kids") %>% 
  mutate(
    # scaled (centered around mean, SD = 1, i.e., z-transformed)
    age = scale(ageInMonths),
    symmetricPosition = scale(symmetricPosition),
    trialNr = trialNr - min(trialNr),
  ) %>% 
  select(subjID, age, ageInMonths, datacollection, symmetricPosition, trialNr, correctBox)

mAgeBox <- brm(correctBox ~ age + datacollection + symmetricPosition + trialNr + (1 + symmetricPosition + trialNr | subjID),
                    data = mDataAgeBox,
                    family = bernoulli(link = "logit"),
                    warmup = 1000, 
                    iter   = 3000, 
                    chains = 4, 
                    inits  = "random",
                    cores  = 4)

write.csv(mAgeBox, "../saves/mAgeBox.csv", quote = F, row.names = F)
saveRDS(mAgeBox, "../saves/mAgeBox.rds")
```

```{r GLMM_plot_box}
# mAgeBox <- readRDS("../saves/mAgeBox.rds")
nd_box <- mDataAgeBox %>% 
  select(-c(correctBox, trialNr)) %>% 
  mutate(trialNr = 0, symmetricPosition = 0)
  
# extract model predictions for mock data
pred_box <- fitted(mAgeBox, newdata = nd_box, re_formula = NA) %>% as_tibble() %>% bind_cols(mDataAgeBox)

box_variation_plot_GLMM <- ggplot() +
  
  # chance level
  geom_segment(aes(x = 3.0, y = 0.2, xend = 6.2, yend = 0.2), lty = "dotted") + 
  geom_segment(aes(x = 6.25, y = 0.125, xend = 6.75, yend = 0.125), lty = "dotted") + 
  
  # use model predictions for smoother
  geom_smooth(
    data = pred_box, 
    aes(x = ageInMonths/12, y = Estimate, ymin = Q2.5, ymax = Q97.5, group = datacollection, lty = datacollection), 
    stat = "identity", size = 0.5, alpha = 0.15, col = "darkgrey",
  ) +
  
  geom_point(
    data = variationBoxInd %>% filter(sample == "kids"), 
    aes(x = ageInYearsExact, y = mean, col = ageInYears, shape = datacollection, alpha = datacollection)
  ) +
  
  geom_pointrange(
    data = variationBox %>% filter(sample == "kids"), 
    aes(x = as.numeric(as.character(ageInYears))+.5, y = mean, ymin = ci_lower, ymax = ci_upper, col = ageInYears, shape = datacollection, alpha = datacollection), size = 0.8, position=position_dodge(width = 0.1)
  ) +
  
  scale_shape_manual(values = c(16, 18)) + 
  scale_alpha_discrete(range = c(1, 0.4)) + 
  scale_linetype_manual(values = c("solid", "dashed")) + 
  
  # adult data
  geom_jitter(
    data = variationBoxInd %>% filter(sample == "adults"), 
    aes(x = 6.5, y = mean, col = ageInYears, shape = datacollection), alpha = 0.5, width = .05, height = .01,  
  ) +

  geom_pointrange(
    data = variationBox %>% filter(sample == "adults"), 
    aes(x = 6.5, y = mean, ymin = ci_lower, ymax = ci_upper, shape = datacollection), 
    size = 0.8,
  ) +
  
  labs(x = "Age in years", y = "Proportion correct", col = "Age in years", shape = "Data collection mode", alpha = "Data collection mode", lty = "Data collection mode") + 
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d", "darkgrey"), breaks = c("3", "4", "5", "18"), labels = c("3-year-olds", "4-year-olds", "5-year-olds", "Adults")) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) + 
  scale_x_continuous(breaks = seq(3, 6.5, 0.5), labels = c("3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "Adults")) + 
  theme(legend.position="none")

box_variation_plot_GLMM

saveRDS(box_variation_plot_GLMM, file = "../saves/tango-box-variation-plot-GLMM.rds")
# ggsave("../figures/tango_box_variation_GLMM.png", width = 7, height = 4)
```

# RELI

```{r reli_data}
reli <- testtrials %>% 
  filter(studytype == "reli" & (ageInYears < 6 | ageInYears == 18) & completedReli == TRUE) %>% 
  mutate(ageInYears = factor(ageInYears, levels = c("3", "4", "5", "18")))

reli %>%
  group_by(subjID) %>%
  slice(1) %>%
  ungroup() %>% 
  select(ageInYears, studyversion) %>%
  ftable()
```

## Splithalf Reliability Data
```{r intCon_hedge_data}
# take data of first reli day for internal consistency
hedge_intCon <- reli %>% 
  filter(studyversion == "hedge" & reliday == "reliday1") %>% 
  mutate(
    testhalf = ifelse(trialNr %% 2 == 0, "even_trials", "odd_trials")
  ) %>% 
  group_by(subjID, testhalf, sample, ageInYears) %>%
  tidyboot_mean(column = clickDistInBalloons, na.rm = TRUE)

hedge_intCon <- hedge_intCon %>% 
  select(-c(n, empirical_stat)) %>% 
  group_by(subjID, testhalf) %>%
  pivot_wider(
    names_from = testhalf,
    values_from = c(mean, ci_lower, ci_upper)
  ) %>%
  ungroup()

# summary
psych::describeBy(hedge_intCon, hedge_intCon$sample)
```

```{r intCon_hedge_kids}
hedge_intCon_kids <- hedge_intCon %>% 
  filter(sample == "kids") %>% 
  ggplot(., aes(x = mean_even_trials, y = mean_odd_trials)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(aes(col = ageInYears), size = 0.7) + 
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d"), guide = "none") +
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 5, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 5), breaks = seq(0, 5, 1)) +
  scale_y_continuous(limits = c(0, 5), breaks = seq(0, 5, 1)) +
  labs(x = "Even trials", y = "Odd trials")

hedge_intCon_kids

saveRDS(hedge_intCon_kids, file = "../saves/tango-hedge-intCon-kids.rds")
# ggsave("../figures/tango_hedge_intCon_kids.png", width = 6, height = 4)
```

```{r intCon_hedge_adults}
hedge_intCon_adults <- hedge_intCon %>% 
  filter(sample == "adults") %>% 
  ggplot(., aes(x = mean_even_trials, y = mean_odd_trials)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(col = "darkgrey", size = 1.2, shape = 18, alpha = 0.5) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 2, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 2), breaks = seq(0, 2, 0.5)) +
  scale_y_continuous(limits = c(0, 2), breaks = seq(0, 2, 0.5)) +
  labs(x = "Even trials", y = "Odd trials")

hedge_intCon_adults

saveRDS(hedge_intCon_adults, file = "../saves/tango-hedge-intCon-adults.rds")
# ggsave("../figures/tango_hedge_intCon_adults.png", width = 6, height = 4)
```

```{r intCon_box_data}
# take data of first reli day for internal consistency
box_intCon <- reli %>% 
  filter(studyversion == "box" & reliday == "reliday1") %>% 
  mutate(
    testhalf = ifelse(trialNr %% 2 == 0, "even_trials", "odd_trials")
  ) %>% 
  group_by(subjID, testhalf, sample, ageInYears) %>%
  tidyboot_mean(column = correctBox, na.rm = TRUE)

box_intCon <- box_intCon %>% 
  select(-c(n, empirical_stat)) %>% 
  group_by(subjID, testhalf) %>%
  pivot_wider(
    names_from = testhalf,
    values_from = c(mean, ci_lower, ci_upper)
  ) %>%
  ungroup()

# summary
psych::describeBy(box_intCon, box_intCon$sample)
```

```{r intCon_box_kids}
box_intCon_kids <- box_intCon %>% 
  filter(sample == "kids") %>% 
  ggplot(., aes(x = mean_even_trials, y = mean_odd_trials)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(aes(col = ageInYears), size = 0.7) + 
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d"), guide = "none") +
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 1, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(breaks = seq(0, 1, 0.2)) +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  labs(x = "Even trials", y = "Odd trials")

box_intCon_kids

saveRDS(box_intCon_kids, file = "../saves/tango-box-intCon-kids.rds")
# ggsave("../figures/tango_box_intCon_kids.png", width = 6, height = 4)
```

```{r intCon_box_adults}
box_intCon_adults <- box_intCon %>% 
  filter(sample == "adults") %>% 
  ggplot(., aes(x = mean_even_trials, y = mean_odd_trials)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(col = "darkgrey", size = 1.2, shape = 18, alpha = 0.5) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 1, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  labs(x = "Even trials", y = "Odd trials")

box_intCon_adults

saveRDS(box_intCon_adults, file = "../saves/tango-box-intCon-adults.rds")
# ggsave("../figures/tango_box_intCon_adults.png", width = 6, height = 4)
```

## Splithalf Reliability - Hedge Kids

```{r splithalfr_hedge_kids_firstsecond}
fn_score_hedge <- function(ds) {
  return(mean(ds$clickDistInBalloons, na.rm = TRUE))
}

hedge_intCon_data <- reli %>%
  filter(studyversion == "hedge" & reliday == "reliday1")

# first-second half split
splitscores_hedge_firstsecond_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  method = c("first_second"),
  ncores = 1,
  verbose = F
)

hedge_firstsecond_kids <- split_coefs(splitscores_hedge_firstsecond_kids, cor)
hedge_firstsecond_kids_ci <- split_ci(splitscores_hedge_firstsecond_kids, cor)

splithalf_data <- tibble(
                          sample = "kids",
                          studyversion = "hedge",
                          method = "first-second",
                          stratification = "none",
                          coefficient = hedge_firstsecond_kids,
                          CI_lower = hedge_firstsecond_kids_ci$lims["0.025","bca"],
                          CI_upper = hedge_firstsecond_kids_ci$lims["0.975","bca"]
                        )

# first-second half stratified by target position
splitscores_hedge_firstsecondStrat_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  method = c("first_second"),
  ncores = 1,
  verbose = F,
  stratification = hedge_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

hedge_firstsecondStrat_kids <- split_coefs(splitscores_hedge_firstsecondStrat_kids, cor)
hedge_firstsecondStrat_kids_ci <- split_ci(splitscores_hedge_firstsecondStrat_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "first-second",
                                        stratification = "target position",
                                        coefficient = hedge_firstsecondStrat_kids,
                                        CI_lower = hedge_firstsecondStrat_kids_ci$lims["0.025","bca"],
                                        CI_upper = hedge_firstsecondStrat_kids_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_hedge_kids_oddeven}
# odd-even split
splitscores_hedge_oddeven_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  method = c("odd_even"),
  ncores = 1,
  verbose = F
)

hedge_oddeven_kids <- split_coefs(splitscores_hedge_oddeven_kids, cor)
hedge_oddeven_kids_ci <- split_ci(splitscores_hedge_oddeven_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "odd-even",
                                        stratification = "none",
                                        coefficient = hedge_oddeven_kids,
                                        CI_lower = hedge_oddeven_kids_ci$lims["0.025","bca"],
                                        CI_upper = hedge_oddeven_kids_ci$lims["0.975","bca"]
                                      )

# odd-even split stratified by target position
splitscores_hedge_oddevenStrat_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  method = c("odd_even"),
  ncores = 1,
  verbose = F,
  stratification = hedge_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

hedge_oddevenStrat_kids <- split_coefs(splitscores_hedge_oddevenStrat_kids, cor)
hedge_oddevenStrat_kids_ci <- split_ci(splitscores_hedge_oddevenStrat_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "odd-even",
                                        stratification = "target position",
                                        coefficient = hedge_oddevenStrat_kids,
                                        CI_lower = hedge_oddevenStrat_kids_ci$lims["0.025","bca"],
                                        CI_upper = hedge_oddevenStrat_kids_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_hedge_kids_permutated}
# permutated splitting (random sampling without replacement)
splitscores_hedge_permutated_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
)

hedge_permutated_kids <- split_coefs(splitscores_hedge_permutated_kids, cor)

splitscores_hedge_permutated_kids_uniq_reps <- unique(splitscores_hedge_permutated_kids$replication)

splitscores_hedge_permutated_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_permutated_kids, replication==r), cor))
}

hedge_permutated_kids_ci <- mclapply(splitscores_hedge_permutated_kids_uniq_reps, splitscores_hedge_permutated_kids_parallel_split_ci, mc.cores=48)

hedge_permutated_kids_tbl <- tibble(
  studyversion = "hedge",
  sample = "kids",
  split = "permutated",
  stratification = "none",
  mean = hedge_permutated_kids)

hedge_permutated_kids_tbl$CI_lower = numeric(nrow(hedge_permutated_kids_tbl))
hedge_permutated_kids_tbl$CI_upper = numeric(nrow(hedge_permutated_kids_tbl))

for(i in 1:nrow(hedge_permutated_kids_tbl)) {
  hedge_permutated_kids_tbl$CI_lower[i] <- hedge_permutated_kids_ci[[i]]$lims["0.025","bca"]
  hedge_permutated_kids_tbl$CI_upper[i] <- hedge_permutated_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "permutated",
                                        stratification = "none",
                                        coefficient = mean(hedge_permutated_kids_tbl$mean),
                                        CI_lower = mean(hedge_permutated_kids_tbl$CI_lower),
                                        CI_upper = mean(hedge_permutated_kids_tbl$CI_upper),
                                      )
```

```{r splithalfr_hedge_kids_permutated_stratified}
# permutated splitting stratified by target position
splitscores_hedge_permutatedStrat_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = hedge_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

hedge_permutatedStrat_kids <- split_coefs(splitscores_hedge_permutatedStrat_kids, cor)

splitscores_hedge_permutatedStrat_kids_uniq_reps <- unique(splitscores_hedge_permutatedStrat_kids$replication)

splitscores_hedge_permutatedStrat_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_permutatedStrat_kids, replication==r), cor))
}

hedge_permutatedStrat_kids_ci <- mclapply(splitscores_hedge_permutatedStrat_kids_uniq_reps, splitscores_hedge_permutatedStrat_kids_parallel_split_ci, mc.cores=48)

hedge_permutatedStrat_kids_tbl <- tibble(
  studyversion = "hedge",
  sample = "kids",
  split = "random",
  stratification = "target position",
  mean = hedge_permutatedStrat_kids)

hedge_permutatedStrat_kids_tbl$CI_lower = numeric(nrow(hedge_permutatedStrat_kids_tbl))
hedge_permutatedStrat_kids_tbl$CI_upper = numeric(nrow(hedge_permutatedStrat_kids_tbl))

for(i in 1:nrow(hedge_permutatedStrat_kids_tbl)) {
  hedge_permutatedStrat_kids_tbl$CI_lower[i] <- hedge_permutatedStrat_kids_ci[[i]]$lims["0.025","bca"]
  hedge_permutatedStrat_kids_tbl$CI_upper[i] <- hedge_permutatedStrat_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "permutated",
                                        stratification = "target position",
                                        coefficient = mean(hedge_permutatedStrat_kids_tbl$mean),
                                        CI_lower = mean(hedge_permutatedStrat_kids_tbl$CI_lower),
                                        CI_upper = mean(hedge_permutatedStrat_kids_tbl$CI_upper),
                                      )
```

```{r splithalfr_hedge_kids_montecarlo}
# monte carlo (sampling with replacement)
splitscores_hedge_montecarlo_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
)

hedge_montecarlo_kids <- split_coefs(splitscores_hedge_montecarlo_kids, cor)

splitscores_hedge_montecarlo_kids_uniq_reps <- unique(splitscores_hedge_montecarlo_kids$replication)

splitscores_hedge_montecarlo_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_montecarlo_kids, replication==r), cor))
}

hedge_montecarlo_kids_ci <- mclapply(splitscores_hedge_montecarlo_kids_uniq_reps, splitscores_hedge_montecarlo_kids_parallel_split_ci, mc.cores=48)

hedge_montecarlo_kids_tbl <- tibble(
  studyversion = "hedge",
  sample = "kids",
  split = "Monte Carlo",
  stratification = "none",
  mean = hedge_montecarlo_kids)

hedge_montecarlo_kids_tbl$CI_lower = numeric(nrow(hedge_montecarlo_kids_tbl))
hedge_montecarlo_kids_tbl$CI_upper = numeric(nrow(hedge_montecarlo_kids_tbl))

for(i in 1:nrow(hedge_montecarlo_kids_tbl)) {
  hedge_montecarlo_kids_tbl$CI_lower[i] <- hedge_montecarlo_kids_ci[[i]]$lims["0.025","bca"]
  hedge_montecarlo_kids_tbl$CI_upper[i] <- hedge_montecarlo_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "Monte Carlo",
                                        stratification = "none",
                                        coefficient = mean(hedge_montecarlo_kids_tbl$mean),
                                        CI_lower = mean(hedge_montecarlo_kids_tbl$CI_lower),
                                        CI_upper = mean(hedge_montecarlo_kids_tbl$CI_upper),
                                      )
```

```{r splithalfr_hedge_kids_montecarlo_stratified}
# monte carlo stratified by target position
splitscores_hedge_montecarloStrat_kids <- by_split(
  hedge_intCon_data %>% filter(sample == "kids"),
  hedge_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = hedge_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

hedge_montecarloStrat_kids <- split_coefs(splitscores_hedge_montecarloStrat_kids, cor)

splitscores_hedge_montecarloStrat_kids_uniq_reps <- unique(splitscores_hedge_montecarloStrat_kids$replication)

splitscores_hedge_montecarloStrat_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_montecarloStrat_kids, replication==r), cor))
}

hedge_montecarloStrat_kids_ci <- mclapply(splitscores_hedge_montecarloStrat_kids_uniq_reps, splitscores_hedge_montecarloStrat_kids_parallel_split_ci, mc.cores=48)

hedge_montecarloStrat_kids_tbl <- tibble(
  studyversion = "hedge",
  sample = "kids",
  split = "Monte Carlo",
  stratification = "target position",
  mean = hedge_montecarloStrat_kids)

hedge_montecarloStrat_kids_tbl$CI_lower = numeric(nrow(hedge_montecarloStrat_kids_tbl))
hedge_montecarloStrat_kids_tbl$CI_upper = numeric(nrow(hedge_montecarloStrat_kids_tbl))

for(i in 1:nrow(hedge_montecarloStrat_kids_tbl)) {
  hedge_montecarloStrat_kids_tbl$CI_lower[i] <- hedge_montecarloStrat_kids_ci[[i]]$lims["0.025","bca"]
  hedge_montecarloStrat_kids_tbl$CI_upper[i] <- hedge_montecarloStrat_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "hedge",
                                        method = "Monte Carlo",
                                        stratification = "target position",
                                        coefficient = mean(hedge_montecarloStrat_kids_tbl$mean),
                                        CI_lower = mean(hedge_montecarloStrat_kids_tbl$CI_lower),
                                        CI_upper = mean(hedge_montecarloStrat_kids_tbl$CI_upper),
                                      )
```

####
## Splithalf Reliability - Hedge Adults

```{r splithalfr_hedge_adults_firstsecond}
# first-second half split
splitscores_hedge_firstsecond_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  method = c("first_second"),
  ncores = 1,
  verbose = F
)

hedge_firstsecond_adults <- split_coefs(splitscores_hedge_firstsecond_adults, cor)
hedge_firstsecond_adults_ci <- split_ci(splitscores_hedge_firstsecond_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "first-second",
                                        stratification = "none",
                                        coefficient = hedge_firstsecond_adults,
                                        CI_lower = hedge_firstsecond_adults_ci$lims["0.025","bca"],
                                        CI_upper = hedge_firstsecond_adults_ci$lims["0.975","bca"]
                                      )

# first-second half stratified by target position
splitscores_hedge_firstsecondStrat_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  method = c("first_second"),
  ncores = 1,
  verbose = F,
  stratification = hedge_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

hedge_firstsecondStrat_adults <- split_coefs(splitscores_hedge_firstsecondStrat_adults, cor)
hedge_firstsecondStrat_adults_ci <- split_ci(splitscores_hedge_firstsecondStrat_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "first-second",
                                        stratification = "target position",
                                        coefficient = hedge_firstsecondStrat_adults,
                                        CI_lower = hedge_firstsecondStrat_adults_ci$lims["0.025","bca"],
                                        CI_upper = hedge_firstsecondStrat_adults_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_hedge_adults_oddeven}
# odd-even split
splitscores_hedge_oddeven_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  method = c("odd_even"),
  ncores = 1,
  verbose = F
)

hedge_oddeven_adults <- split_coefs(splitscores_hedge_oddeven_adults, cor)
hedge_oddeven_adults_ci <- split_ci(splitscores_hedge_oddeven_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "odd-even",
                                        stratification = "none",
                                        coefficient = hedge_oddeven_adults,
                                        CI_lower = hedge_oddeven_adults_ci$lims["0.025","bca"],
                                        CI_upper = hedge_oddeven_adults_ci$lims["0.975","bca"]
                                      )

# odd-even split stratified by target position
splitscores_hedge_oddevenStrat_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  method = c("odd_even"),
  ncores = 1,
  verbose = F,
  stratification = hedge_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

hedge_oddevenStrat_adults <- split_coefs(splitscores_hedge_oddevenStrat_adults, cor)
hedge_oddevenStrat_adults_ci <- split_ci(splitscores_hedge_oddevenStrat_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "odd-even",
                                        stratification = "target position",
                                        coefficient = hedge_oddevenStrat_adults,
                                        CI_lower = hedge_oddevenStrat_adults_ci$lims["0.025","bca"],
                                        CI_upper = hedge_oddevenStrat_adults_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_hedge_adults_permutated}
# permutated splitting (random sampling without replacement)
splitscores_hedge_permutated_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
)

hedge_permutated_adults <- split_coefs(splitscores_hedge_permutated_adults, cor)

splitscores_hedge_permutated_adults_uniq_reps <- unique(splitscores_hedge_permutated_adults$replication)

splitscores_hedge_permutated_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_permutated_adults, replication==r), cor))
}

hedge_permutated_adults_ci <- mclapply(splitscores_hedge_permutated_adults_uniq_reps, splitscores_hedge_permutated_adults_parallel_split_ci, mc.cores=48)

hedge_permutated_adults_tbl <- tibble(
  studyversion = "hedge",
  sample = "adults",
  split = "permutated",
  stratification = "none",
  mean = hedge_permutated_adults)

hedge_permutated_adults_tbl$CI_lower = numeric(nrow(hedge_permutated_adults_tbl))
hedge_permutated_adults_tbl$CI_upper = numeric(nrow(hedge_permutated_adults_tbl))

for(i in 1:nrow(hedge_permutated_adults_tbl)) {
  hedge_permutated_adults_tbl$CI_lower[i] <- hedge_permutated_adults_ci[[i]]$lims["0.025","bca"]
  hedge_permutated_adults_tbl$CI_upper[i] <- hedge_permutated_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "permutated",
                                        stratification = "none",
                                        coefficient = mean(hedge_permutated_adults_tbl$mean),
                                        CI_lower = mean(hedge_permutated_adults_tbl$CI_lower),
                                        CI_upper = mean(hedge_permutated_adults_tbl$CI_upper),
                                      )
```

```{r splithalfr_hedge_adults_permutated_stratified}
# permutated splitting stratified by target position
splitscores_hedge_permutatedStrat_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = hedge_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

hedge_permutatedStrat_adults <- split_coefs(splitscores_hedge_permutatedStrat_adults, cor)

splitscores_hedge_permutatedStrat_adults_uniq_reps <- unique(splitscores_hedge_permutatedStrat_adults$replication)

splitscores_hedge_permutatedStrat_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_permutatedStrat_adults, replication==r), cor))
}

hedge_permutatedStrat_adults_ci <- mclapply(splitscores_hedge_permutatedStrat_adults_uniq_reps, splitscores_hedge_permutatedStrat_adults_parallel_split_ci, mc.cores=48)

hedge_permutatedStrat_adults_tbl <- tibble(
  studyversion = "hedge",
  sample = "adults",
  split = "random",
  stratification = "target position",
  mean = hedge_permutatedStrat_adults)

hedge_permutatedStrat_adults_tbl$CI_lower = numeric(nrow(hedge_permutatedStrat_adults_tbl))
hedge_permutatedStrat_adults_tbl$CI_upper = numeric(nrow(hedge_permutatedStrat_adults_tbl))

for(i in 1:nrow(hedge_permutatedStrat_adults_tbl)) {
  hedge_permutatedStrat_adults_tbl$CI_lower[i] <- hedge_permutatedStrat_adults_ci[[i]]$lims["0.025","bca"]
  hedge_permutatedStrat_adults_tbl$CI_upper[i] <- hedge_permutatedStrat_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "permutated",
                                        stratification = "target position",
                                        coefficient = mean(hedge_permutatedStrat_adults_tbl$mean),
                                        CI_lower = mean(hedge_permutatedStrat_adults_tbl$CI_lower),
                                        CI_upper = mean(hedge_permutatedStrat_adults_tbl$CI_upper),
                                      )
```

```{r splithalfr_hedge_adults_montecarlo}
# monte carlo (sampling with replacement)
splitscores_hedge_montecarlo_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
)

hedge_montecarlo_adults <- split_coefs(splitscores_hedge_montecarlo_adults, cor)

splitscores_hedge_montecarlo_adults_uniq_reps <- unique(splitscores_hedge_montecarlo_adults$replication)

splitscores_hedge_montecarlo_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_montecarlo_adults, replication==r), cor))
}

hedge_montecarlo_adults_ci <- mclapply(splitscores_hedge_montecarlo_adults_uniq_reps, splitscores_hedge_montecarlo_adults_parallel_split_ci, mc.cores=48)

hedge_montecarlo_adults_tbl <- tibble(
  studyversion = "hedge",
  sample = "adults",
  split = "Monte Carlo",
  stratification = "none",
  mean = hedge_montecarlo_adults)

hedge_montecarlo_adults_tbl$CI_lower = numeric(nrow(hedge_montecarlo_adults_tbl))
hedge_montecarlo_adults_tbl$CI_upper = numeric(nrow(hedge_montecarlo_adults_tbl))

for(i in 1:nrow(hedge_montecarlo_adults_tbl)) {
  hedge_montecarlo_adults_tbl$CI_lower[i] <- hedge_montecarlo_adults_ci[[i]]$lims["0.025","bca"]
  hedge_montecarlo_adults_tbl$CI_upper[i] <- hedge_montecarlo_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "Monte Carlo",
                                        stratification = "none",
                                        coefficient = mean(hedge_montecarlo_adults_tbl$mean),
                                        CI_lower = mean(hedge_montecarlo_adults_tbl$CI_lower),
                                        CI_upper = mean(hedge_montecarlo_adults_tbl$CI_upper),
                                      )
```

```{r splithalfr_hedge_adults_montecarlo_stratified}
# monte carlo stratified by target position
splitscores_hedge_montecarloStrat_adults <- by_split(
  hedge_intCon_data %>% filter(sample == "adults"),
  hedge_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_hedge,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = hedge_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

hedge_montecarloStrat_adults <- split_coefs(splitscores_hedge_montecarloStrat_adults, cor)

splitscores_hedge_montecarloStrat_adults_uniq_reps <- unique(splitscores_hedge_montecarloStrat_adults$replication)

splitscores_hedge_montecarloStrat_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_hedge_montecarloStrat_adults, replication==r), cor))
}

hedge_montecarloStrat_adults_ci <- mclapply(splitscores_hedge_montecarloStrat_adults_uniq_reps, splitscores_hedge_montecarloStrat_adults_parallel_split_ci, mc.cores=48)

hedge_montecarloStrat_adults_tbl <- tibble(
  studyversion = "hedge",
  sample = "adults",
  split = "Monte Carlo",
  stratification = "target position",
  mean = hedge_montecarloStrat_adults)

hedge_montecarloStrat_adults_tbl$CI_lower = numeric(nrow(hedge_montecarloStrat_adults_tbl))
hedge_montecarloStrat_adults_tbl$CI_upper = numeric(nrow(hedge_montecarloStrat_adults_tbl))

for(i in 1:nrow(hedge_montecarloStrat_adults_tbl)) {
  hedge_montecarloStrat_adults_tbl$CI_lower[i] <- hedge_montecarloStrat_adults_ci[[i]]$lims["0.025","bca"]
  hedge_montecarloStrat_adults_tbl$CI_upper[i] <- hedge_montecarloStrat_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "hedge",
                                        method = "Monte Carlo",
                                        stratification = "target position",
                                        coefficient = mean(hedge_montecarloStrat_adults_tbl$mean),
                                        CI_lower = mean(hedge_montecarloStrat_adults_tbl$CI_lower),
                                        CI_upper = mean(hedge_montecarloStrat_adults_tbl$CI_upper),
                                      )
```


## Splithalf Reliability - Box Kids

```{r splithalfr_box_kids_firstsecond}
fn_score_box <- function(ds) {
  return(mean(ds$correctBox, na.rm = TRUE))
}

box_intCon_data <- reli %>%
  filter(studyversion == "box" & reliday == "reliday1")

# first-second half split
splitscores_box_firstsecond_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  method = c("first_second"),
  ncores = 1,
  verbose = F
)

box_firstsecond_kids <- split_coefs(splitscores_box_firstsecond_kids, cor)
box_firstsecond_kids_ci <- split_ci(splitscores_box_firstsecond_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "first-second",
                                        stratification = "none",
                                        coefficient = box_firstsecond_kids,
                                        CI_lower = box_firstsecond_kids_ci$lims["0.025","bca"],
                                        CI_upper = box_firstsecond_kids_ci$lims["0.975","bca"]
                                      )

# first-second half stratified by target position
splitscores_box_firstsecondStrat_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  method = c("first_second"),
  ncores = 1,
  verbose = F,
  stratification = box_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

box_firstsecondStrat_kids <- split_coefs(splitscores_box_firstsecondStrat_kids, cor)
box_firstsecondStrat_kids_ci <- split_ci(splitscores_box_firstsecondStrat_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "first-second",
                                        stratification = "target position",
                                        coefficient = box_firstsecondStrat_kids,
                                        CI_lower = box_firstsecondStrat_kids_ci$lims["0.025","bca"],
                                        CI_upper = box_firstsecondStrat_kids_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_box_kids_oddeven}
# odd-even split
splitscores_box_oddeven_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  method = c("odd_even"),
  ncores = 1,
  verbose = F
)

box_oddeven_kids <- split_coefs(splitscores_box_oddeven_kids, cor)
box_oddeven_kids_ci <- split_ci(splitscores_box_oddeven_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "odd-even",
                                        stratification = "none",
                                        coefficient = box_oddeven_kids,
                                        CI_lower = box_oddeven_kids_ci$lims["0.025","bca"],
                                        CI_upper = box_oddeven_kids_ci$lims["0.975","bca"]
                                      )

# odd-even split stratified by target position
splitscores_box_oddevenStrat_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  method = c("odd_even"),
  ncores = 1,
  verbose = F,
  stratification = box_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

box_oddevenStrat_kids <- split_coefs(splitscores_box_oddevenStrat_kids, cor)
box_oddevenStrat_kids_ci <- split_ci(splitscores_box_oddevenStrat_kids, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "odd-even",
                                        stratification = "target position",
                                        coefficient = box_oddevenStrat_kids,
                                        CI_lower = box_oddevenStrat_kids_ci$lims["0.025","bca"],
                                        CI_upper = box_oddevenStrat_kids_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_box_kids_permutated}
# permutated splitting (random sampling without replacement)
splitscores_box_permutated_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
)

box_permutated_kids <- split_coefs(splitscores_box_permutated_kids, cor)

splitscores_box_permutated_kids_uniq_reps <- unique(splitscores_box_permutated_kids$replication)

splitscores_box_permutated_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_permutated_kids, replication==r), cor))
}

box_permutated_kids_ci <- mclapply(splitscores_box_permutated_kids_uniq_reps, splitscores_box_permutated_kids_parallel_split_ci, mc.cores=48)

box_permutated_kids_tbl <- tibble(
  studyversion = "box",
  sample = "kids",
  split = "permutated",
  stratification = "none",
  mean = box_permutated_kids)

box_permutated_kids_tbl$CI_lower = numeric(nrow(box_permutated_kids_tbl))
box_permutated_kids_tbl$CI_upper = numeric(nrow(box_permutated_kids_tbl))

for(i in 1:nrow(box_permutated_kids_tbl)) {
  box_permutated_kids_tbl$CI_lower[i] <- box_permutated_kids_ci[[i]]$lims["0.025","bca"]
  box_permutated_kids_tbl$CI_upper[i] <- box_permutated_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "permutated",
                                        stratification = "none",
                                        coefficient = mean(box_permutated_kids_tbl$mean),
                                        CI_lower = mean(box_permutated_kids_tbl$CI_lower),
                                        CI_upper = mean(box_permutated_kids_tbl$CI_upper),
                                      )
```

```{r splithalfr_box_kids_permutated_stratified}
# permutated splitting stratified by target position
splitscores_box_permutatedStrat_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = box_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

box_permutatedStrat_kids <- split_coefs(splitscores_box_permutatedStrat_kids, cor)

splitscores_box_permutatedStrat_kids_uniq_reps <- unique(splitscores_box_permutatedStrat_kids$replication)

splitscores_box_permutatedStrat_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_permutatedStrat_kids, replication==r), cor))
}

box_permutatedStrat_kids_ci <- mclapply(splitscores_box_permutatedStrat_kids_uniq_reps, splitscores_box_permutatedStrat_kids_parallel_split_ci, mc.cores=48)

box_permutatedStrat_kids_tbl <- tibble(
  studyversion = "box",
  sample = "kids",
  split = "random",
  stratification = "target position",
  mean = box_permutatedStrat_kids)

box_permutatedStrat_kids_tbl$CI_lower = numeric(nrow(box_permutatedStrat_kids_tbl))
box_permutatedStrat_kids_tbl$CI_upper = numeric(nrow(box_permutatedStrat_kids_tbl))

for(i in 1:nrow(box_permutatedStrat_kids_tbl)) {
  box_permutatedStrat_kids_tbl$CI_lower[i] <- box_permutatedStrat_kids_ci[[i]]$lims["0.025","bca"]
  box_permutatedStrat_kids_tbl$CI_upper[i] <- box_permutatedStrat_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "permutated",
                                        stratification = "target position",
                                        coefficient = mean(box_permutatedStrat_kids_tbl$mean),
                                        CI_lower = mean(box_permutatedStrat_kids_tbl$CI_lower),
                                        CI_upper = mean(box_permutatedStrat_kids_tbl$CI_upper),
                                      )
```

```{r splithalfr_box_kids_montecarlo}
# monte carlo (sampling with replacement)
splitscores_box_montecarlo_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
)

box_montecarlo_kids <- split_coefs(splitscores_box_montecarlo_kids, cor)

splitscores_box_montecarlo_kids_uniq_reps <- unique(splitscores_box_montecarlo_kids$replication)

splitscores_box_montecarlo_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_montecarlo_kids, replication==r), cor))
}

box_montecarlo_kids_ci <- mclapply(splitscores_box_montecarlo_kids_uniq_reps, splitscores_box_montecarlo_kids_parallel_split_ci, mc.cores=48)

box_montecarlo_kids_tbl <- tibble(
  studyversion = "box",
  sample = "kids",
  split = "Monte Carlo",
  stratification = "none",
  mean = box_montecarlo_kids)

box_montecarlo_kids_tbl$CI_lower = numeric(nrow(box_montecarlo_kids_tbl))
box_montecarlo_kids_tbl$CI_upper = numeric(nrow(box_montecarlo_kids_tbl))

for(i in 1:nrow(box_montecarlo_kids_tbl)) {
  box_montecarlo_kids_tbl$CI_lower[i] <- box_montecarlo_kids_ci[[i]]$lims["0.025","bca"]
  box_montecarlo_kids_tbl$CI_upper[i] <- box_montecarlo_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "Monte Carlo",
                                        stratification = "none",
                                        coefficient = mean(box_montecarlo_kids_tbl$mean),
                                        CI_lower = mean(box_montecarlo_kids_tbl$CI_lower),
                                        CI_upper = mean(box_montecarlo_kids_tbl$CI_upper),
                                      )
```

```{r splithalfr_box_kids_montecarlo_stratified}
# monte carlo stratified by target position
splitscores_box_montecarloStrat_kids <- by_split(
  box_intCon_data %>% filter(sample == "kids"),
  box_intCon_data %>% filter(sample == "kids") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = box_intCon_data %>% filter(sample == "kids") %>% pull(symmetricPosition),
)

box_montecarloStrat_kids <- split_coefs(splitscores_box_montecarloStrat_kids, cor)

splitscores_box_montecarloStrat_kids_uniq_reps <- unique(splitscores_box_montecarloStrat_kids$replication)

splitscores_box_montecarloStrat_kids_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_montecarloStrat_kids, replication==r), cor))
}

box_montecarloStrat_kids_ci <- mclapply(splitscores_box_montecarloStrat_kids_uniq_reps, splitscores_box_montecarloStrat_kids_parallel_split_ci, mc.cores=48)

box_montecarloStrat_kids_tbl <- tibble(
  studyversion = "box",
  sample = "kids",
  split = "Monte Carlo",
  stratification = "target position",
  mean = box_montecarloStrat_kids)

box_montecarloStrat_kids_tbl$CI_lower = numeric(nrow(box_montecarloStrat_kids_tbl))
box_montecarloStrat_kids_tbl$CI_upper = numeric(nrow(box_montecarloStrat_kids_tbl))

for(i in 1:nrow(box_montecarloStrat_kids_tbl)) {
  box_montecarloStrat_kids_tbl$CI_lower[i] <- box_montecarloStrat_kids_ci[[i]]$lims["0.025","bca"]
  box_montecarloStrat_kids_tbl$CI_upper[i] <- box_montecarloStrat_kids_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "kids",
                                        studyversion = "box",
                                        method = "Monte Carlo",
                                        stratification = "target position",
                                        coefficient = mean(box_montecarloStrat_kids_tbl$mean),
                                        CI_lower = mean(box_montecarloStrat_kids_tbl$CI_lower),
                                        CI_upper = mean(box_montecarloStrat_kids_tbl$CI_upper),
                                      )
```

## Splithalf Reliability - Box Adults

```{r splithalfr_box_adults_firstsecond}
# first-second half split
splitscores_box_firstsecond_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  method = c("first_second"),
  ncores = 1,
  verbose = F
)

box_firstsecond_adults <- split_coefs(splitscores_box_firstsecond_adults, cor)
box_firstsecond_adults_ci <- split_ci(splitscores_box_firstsecond_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "first-second",
                                        stratification = "none",
                                        coefficient = box_firstsecond_adults,
                                        CI_lower = box_firstsecond_adults_ci$lims["0.025","bca"],
                                        CI_upper = box_firstsecond_adults_ci$lims["0.975","bca"]
                                      )

# first-second half stratified by target position
splitscores_box_firstsecondStrat_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  method = c("first_second"),
  ncores = 1,
  verbose = F,
  stratification = box_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

box_firstsecondStrat_adults <- split_coefs(splitscores_box_firstsecondStrat_adults, cor)
box_firstsecondStrat_adults_ci <- split_ci(splitscores_box_firstsecondStrat_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "first-second",
                                        stratification = "target position",
                                        coefficient = box_firstsecondStrat_adults,
                                        CI_lower = box_firstsecondStrat_adults_ci$lims["0.025","bca"],
                                        CI_upper = box_firstsecondStrat_adults_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_box_adults_oddeven}
# odd-even split
splitscores_box_oddeven_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  method = c("odd_even"),
  ncores = 1,
  verbose = F
)

box_oddeven_adults <- split_coefs(splitscores_box_oddeven_adults, cor)
box_oddeven_adults_ci <- split_ci(splitscores_box_oddeven_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "odd-even",
                                        stratification = "none",
                                        coefficient = box_oddeven_adults,
                                        CI_lower = box_oddeven_adults_ci$lims["0.025","bca"],
                                        CI_upper = box_oddeven_adults_ci$lims["0.975","bca"]
                                      )

# odd-even split stratified by target position
splitscores_box_oddevenStrat_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  method = c("odd_even"),
  ncores = 1,
  verbose = F,
  stratification = box_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

box_oddevenStrat_adults <- split_coefs(splitscores_box_oddevenStrat_adults, cor)
box_oddevenStrat_adults_ci <- split_ci(splitscores_box_oddevenStrat_adults, cor)

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "odd-even",
                                        stratification = "target position",
                                        coefficient = box_oddevenStrat_adults,
                                        CI_lower = box_oddevenStrat_adults_ci$lims["0.025","bca"],
                                        CI_upper = box_oddevenStrat_adults_ci$lims["0.975","bca"]
                                      )
```

```{r splithalfr_box_adults_permutated}
# permutated splitting (random sampling without replacement)
splitscores_box_permutated_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
)

box_permutated_adults <- split_coefs(splitscores_box_permutated_adults, cor)

splitscores_box_permutated_adults_uniq_reps <- unique(splitscores_box_permutated_adults$replication)

splitscores_box_permutated_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_permutated_adults, replication==r), cor))
}

box_permutated_adults_ci <- mclapply(splitscores_box_permutated_adults_uniq_reps, splitscores_box_permutated_adults_parallel_split_ci, mc.cores=48)

box_permutated_adults_tbl <- tibble(
  studyversion = "box",
  sample = "adults",
  split = "permutated",
  stratification = "none",
  mean = box_permutated_adults)

box_permutated_adults_tbl$CI_lower = numeric(nrow(box_permutated_adults_tbl))
box_permutated_adults_tbl$CI_upper = numeric(nrow(box_permutated_adults_tbl))

for(i in 1:nrow(box_permutated_adults_tbl)) {
  box_permutated_adults_tbl$CI_lower[i] <- box_permutated_adults_ci[[i]]$lims["0.025","bca"]
  box_permutated_adults_tbl$CI_upper[i] <- box_permutated_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "permutated",
                                        stratification = "none",
                                        coefficient = mean(box_permutated_adults_tbl$mean),
                                        CI_lower = mean(box_permutated_adults_tbl$CI_lower),
                                        CI_upper = mean(box_permutated_adults_tbl$CI_upper),
                                      )
```

```{r splithalfr_box_adults_permutated_stratified}
# permutated splitting stratified by target position
splitscores_box_permutatedStrat_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = box_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

box_permutatedStrat_adults <- split_coefs(splitscores_box_permutatedStrat_adults, cor)

splitscores_box_permutatedStrat_adults_uniq_reps <- unique(splitscores_box_permutatedStrat_adults$replication)

splitscores_box_permutatedStrat_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_permutatedStrat_adults, replication==r), cor))
}

box_permutatedStrat_adults_ci <- mclapply(splitscores_box_permutatedStrat_adults_uniq_reps, splitscores_box_permutatedStrat_adults_parallel_split_ci, mc.cores=48)

box_permutatedStrat_adults_tbl <- tibble(
  studyversion = "box",
  sample = "adults",
  split = "random",
  stratification = "target position",
  mean = box_permutatedStrat_adults)

box_permutatedStrat_adults_tbl$CI_lower = numeric(nrow(box_permutatedStrat_adults_tbl))
box_permutatedStrat_adults_tbl$CI_upper = numeric(nrow(box_permutatedStrat_adults_tbl))

for(i in 1:nrow(box_permutatedStrat_adults_tbl)) {
  box_permutatedStrat_adults_tbl$CI_lower[i] <- box_permutatedStrat_adults_ci[[i]]$lims["0.025","bca"]
  box_permutatedStrat_adults_tbl$CI_upper[i] <- box_permutatedStrat_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "permutated",
                                        stratification = "target position",
                                        coefficient = mean(box_permutatedStrat_adults_tbl$mean),
                                        CI_lower = mean(box_permutatedStrat_adults_tbl$CI_lower),
                                        CI_upper = mean(box_permutatedStrat_adults_tbl$CI_upper),
                                      )
```

```{r splithalfr_box_adults_montecarlo}
# monte carlo (sampling with replacement)
splitscores_box_montecarlo_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
)

box_montecarlo_adults <- split_coefs(splitscores_box_montecarlo_adults, cor)

splitscores_box_montecarlo_adults_uniq_reps <- unique(splitscores_box_montecarlo_adults$replication)

splitscores_box_montecarlo_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_montecarlo_adults, replication==r), cor))
}

box_montecarlo_adults_ci <- mclapply(splitscores_box_montecarlo_adults_uniq_reps, splitscores_box_montecarlo_adults_parallel_split_ci, mc.cores=48)

box_montecarlo_adults_tbl <- tibble(
  studyversion = "box",
  sample = "adults",
  split = "Monte Carlo",
  stratification = "none",
  mean = box_montecarlo_adults)

box_montecarlo_adults_tbl$CI_lower = numeric(nrow(box_montecarlo_adults_tbl))
box_montecarlo_adults_tbl$CI_upper = numeric(nrow(box_montecarlo_adults_tbl))

for(i in 1:nrow(box_montecarlo_adults_tbl)) {
  box_montecarlo_adults_tbl$CI_lower[i] <- box_montecarlo_adults_ci[[i]]$lims["0.025","bca"]
  box_montecarlo_adults_tbl$CI_upper[i] <- box_montecarlo_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "Monte Carlo",
                                        stratification = "none",
                                        coefficient = mean(box_montecarlo_adults_tbl$mean),
                                        CI_lower = mean(box_montecarlo_adults_tbl$CI_lower),
                                        CI_upper = mean(box_montecarlo_adults_tbl$CI_upper),
                                      )
```

```{r splithalfr_box_adults_montecarlo_stratified}
# monte carlo stratified by target position
splitscores_box_montecarloStrat_adults <- by_split(
  box_intCon_data %>% filter(sample == "adults"),
  box_intCon_data %>% filter(sample == "adults") %>% pull(subjID),
  fn_score_box,
  replications = 5000,
  method = c("random"),
  replace = TRUE,
  split_p = 1,
  ncores = 100, # setting ncores equally to something less than detectCores()
  stratification = box_intCon_data %>% filter(sample == "adults") %>% pull(symmetricPosition),
)

box_montecarloStrat_adults <- split_coefs(splitscores_box_montecarloStrat_adults, cor)

splitscores_box_montecarloStrat_adults_uniq_reps <- unique(splitscores_box_montecarloStrat_adults$replication)

splitscores_box_montecarloStrat_adults_parallel_split_ci <- function(r) {
        return(split_ci(filter(splitscores_box_montecarloStrat_adults, replication==r), cor))
}

box_montecarloStrat_adults_ci <- mclapply(splitscores_box_montecarloStrat_adults_uniq_reps, splitscores_box_montecarloStrat_adults_parallel_split_ci, mc.cores=48)

box_montecarloStrat_adults_tbl <- tibble(
  studyversion = "box",
  sample = "adults",
  split = "Monte Carlo",
  stratification = "target position",
  mean = box_montecarloStrat_adults)

box_montecarloStrat_adults_tbl$CI_lower = numeric(nrow(box_montecarloStrat_adults_tbl))
box_montecarloStrat_adults_tbl$CI_upper = numeric(nrow(box_montecarloStrat_adults_tbl))

for(i in 1:nrow(box_montecarloStrat_adults_tbl)) {
  box_montecarloStrat_adults_tbl$CI_lower[i] <- box_montecarloStrat_adults_ci[[i]]$lims["0.025","bca"]
  box_montecarloStrat_adults_tbl$CI_upper[i] <- box_montecarloStrat_adults_ci[[i]]$lims["0.975","bca"]
}

splithalf_data <- splithalf_data %>% add_row(
                                        sample = "adults",
                                        studyversion = "box",
                                        method = "Monte Carlo",
                                        stratification = "target position",
                                        coefficient = mean(box_montecarloStrat_adults_tbl$mean),
                                        CI_lower = mean(box_montecarloStrat_adults_tbl$CI_lower),
                                        CI_upper = mean(box_montecarloStrat_adults_tbl$CI_upper),
                                      )
```

## Splithalf Reliability Table & Plot
```{r splithalf_plot}
splithalf_plot <- splithalf_data %>%
  mutate(
    sample = factor(sample, levels = c("kids", "adults"), labels = c("children", "adults")),
  ) %>%
  unite("samplegroup", c(studyversion, sample), sep = " - ", remove = FALSE) %>%
  mutate(samplegroup = fct_rev(samplegroup)) %>%
  unite("methodStrat", c(method, stratification), sep = " - ", remove = FALSE) %>%
  mutate(
    methodStrat = factor(methodStrat, levels = c("first-second - none", "first-second - target position", "odd-even - none", "odd-even - target position", "permutated - none", "permutated - target position", "Monte Carlo - none", "Monte Carlo - target position")) %>% fct_rev(),
  ) %>%
  ggplot(aes(x = methodStrat, y = coefficient, color = sample, group = studyversion)) +
    geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper), colour = "black", width = .1, position = position_dodge(0.1)) +
    geom_point(position = position_dodge(0.1), size = 3) +
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
    scale_color_manual(values = c("#006c66", "darkgrey"), guide = "none") +
    labs(x = "Splitting & stratification method", y = "") +
    coord_flip() +
    facet_wrap(~ samplegroup, nrow = 1) +
    theme(legend.position = "none", panel.spacing = unit(1.5, "lines"))

splithalf_plot
saveRDS(splithalf_plot, file = "../saves/tango-splithalf-plot.rds")

ggsave("../figures/tango_splithalf.png", width = 8, height = 2.5, scale = 1.2)
```

```{r splithalf_table}
knitr::kable(splithalf_data)
```

```{r save_splithalf_data}
write.csv(splithalf_data, "../saves/tango-splithalf.csv", quote = F, row.names = F)
saveRDS(splithalf_data, file = "../saves/tango-splithalf-table.rds")

# clean up
rm(list = ls(pattern = "^splitscores"))
```

## Test-retest Reliability - Hedge

```{r retest_hedge_data}
hedge_retest <- reli %>% 
  filter(studyversion == "hedge") %>% 
  group_by(subjID, reliday, sample, ageInYears) %>% 
  tidyboot_mean(column = clickDistInBalloons, na.rm = TRUE)

hedge_retest <- hedge_retest %>% 
  select(-c(n, empirical_stat)) %>% 
  group_by(subjID, reliday) %>%
  pivot_wider(
    names_from = reliday,
    values_from = c(mean, ci_lower, ci_upper)
  ) %>%
  ungroup()

# summary
psych::describeBy(hedge_retest, hedge_retest$sample)

# calculate at which values we would start seing data as outliers
hedge_retest %>% 
  group_by(sample) %>%
  summarize(
    lower_reliday1 = mean(mean_reliday1) - 3*sd(mean_reliday1), 
    upper_reliday1 = mean(mean_reliday1) + 3*sd(mean_reliday1),
    lower_reliday2 = mean(mean_reliday2) - 3*sd(mean_reliday2),
    upper_reliday2 = mean(mean_reliday2) + 3*sd(mean_reliday2),
  )

# check how many there are
hedge_retest %>% 
  group_by(sample) %>%
  filter(mean_reliday1 >= mean(mean_reliday1) + 3*sd(mean_reliday1) | 
         mean_reliday1 <= mean(mean_reliday1) - 3*sd(mean_reliday1) |
         mean_reliday2 >= mean(mean_reliday2) + 3*sd(mean_reliday2) |
         mean_reliday2 <= mean(mean_reliday2) - 3*sd(mean_reliday2))
```

```{r retest_hedge_model}
# define data
mDataRetestHedge <- reli %>% 
  filter(studyversion == "hedge" & sample == "kids") %>% 
  mutate(
    # scaled (centered around mean, SD = 1, i.e., z-transformed)
    age = scale(ageInMonths, center = TRUE, scale = TRUE)[,1], 
  ) %>% 
  select(subjID, age, reliday, clickDistInBalloons)

# run model
mRetestHedge <- brm(clickDistInBalloons ~ age + (0 + reliday | subjID), 
                              data   = mDataRetestHedge, 
                              family = lognormal(), 
                              warmup = 1000, 
                              iter   = 3000, 
                              chains = 4, 
                              inits  = "random",
                              cores  = 100)

write.csv(mRetestHedge, "../saves/mRetestHedge.csv", quote = F, row.names = F)
saveRDS(mRetestHedge, "../saves/mRetestHedge.rds")
```

```{r retest_hedge_exclude_outliers}
# exclude outliers
hedge_retest_all <- hedge_retest
    
hedge_retest <- hedge_retest_all %>%
  group_by(sample) %>%
  filter(mean_reliday1 <= mean(mean_reliday1) + 3*sd(mean_reliday1),
         mean_reliday1 >= mean(mean_reliday1) - 3*sd(mean_reliday1),
         mean_reliday2 <= mean(mean_reliday2) + 3*sd(mean_reliday2), 
         mean_reliday2 >= mean(mean_reliday2) - 3*sd(mean_reliday2))
  
# see how subject exclusion influences the retest correlation
hedge_retest_correlationcoefficients <- rbind(
  (hedge_retest %>%
  group_by(sample) %>%
  summarise(
    n = n_distinct(subjID),
    pearson_retest = cor(mean_reliday1, mean_reliday2, method = "pearson") %>% round(2), 
    analysis = "outlier excluded",
  )), 
  (hedge_retest_all %>%
  group_by(sample) %>%
  summarise(
    n = n_distinct(subjID),
    pearson_retest = cor(mean_reliday1, mean_reliday2, method = "pearson") %>% round(2), 
    analysis = "outlier included",
  )))

hedge_retest_correlationcoefficients

saveRDS(hedge_retest_correlationcoefficients, file = "../saves/tango-hedge-retest-correlationcoefficients.rds")
```

```{r retest_hedge_kids}
hedge_retest_kids <- hedge_retest %>% 
  filter(sample == "kids") %>% 
  ggplot(., aes(x = mean_reliday1, y = mean_reliday2)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(aes(col = ageInYears), size = 0.7) + 
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d"), guide = "none") +
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 5, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 5), breaks = seq(0, 5, 1)) +
  scale_y_continuous(limits = c(0, 5), breaks = seq(0, 5, 1)) +
  labs(x = "Testday 1", y = "Testday 2")

hedge_retest_kids

saveRDS(hedge_retest_kids, file = "../saves/tango-hedge-retest-kids.rds")
# ggsave("../figures/tango_hedge_retest_kids.png", width = 6, height = 4)
```

```{r retest_hedge_adults}
hedge_retest_adults <- hedge_retest %>% 
  filter(sample == "adults") %>% 
  ggplot(., aes(x = mean_reliday1, y = mean_reliday2)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(col = "darkgrey", size = 1.2, shape = 18, alpha = 0.5) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 2, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 2), breaks = seq(0, 2, 0.5)) +
  scale_y_continuous(limits = c(0, 2), breaks = seq(0, 2, 0.5)) +
  labs(x = "Testday 1", y = "Testday 2")

hedge_retest_adults

saveRDS(hedge_retest_adults, file = "../saves/tango-hedge-retest-adults.rds")
# ggsave("../figures/tango_hedge_retest_adults.png", width = 6, height = 4)
```

## Test-retest Reliability - Box 

```{r retest_box_data}
box_retest <- reli %>% 
  filter(studyversion == "box") %>% 
  group_by(subjID, reliday, sample, ageInYears) %>% 
  tidyboot_mean(column = correctBox, na.rm = TRUE)

box_retest <- box_retest %>% 
  select(-c(n, empirical_stat)) %>% 
  group_by(subjID, reliday) %>%
  pivot_wider(
    names_from = reliday,
    values_from = c(mean, ci_lower, ci_upper)
  ) %>%
  ungroup()

# summary
psych::describeBy(box_retest, box_retest$sample)

####
# calculate at which values we would start seing data as outliers
box_retest %>% 
  group_by(sample) %>%
  summarize(
    lower_reliday1 = mean(mean_reliday1, na.rm = T) - 3*sd(mean_reliday1, na.rm = T), 
    upper_reliday1 = mean(mean_reliday1, na.rm = T) + 3*sd(mean_reliday1, na.rm = T),
    lower_reliday2 = mean(mean_reliday2, na.rm = T) - 3*sd(mean_reliday2, na.rm = T),
    upper_reliday2 = mean(mean_reliday2, na.rm = T) + 3*sd(mean_reliday2, na.rm = T),
  )

# check how many there are => there are none!
box_retest %>% 
  group_by(sample) %>%
  filter(mean_reliday1 >= mean(mean_reliday1, na.rm = T) + 3*sd(mean_reliday1, na.rm = T) | 
         mean_reliday1 <= mean(mean_reliday1, na.rm = T) - 3*sd(mean_reliday1, na.rm = T) |
         mean_reliday2 >= mean(mean_reliday2, na.rm = T) + 3*sd(mean_reliday2, na.rm = T) |
         mean_reliday2 <= mean(mean_reliday2, na.rm = T) - 3*sd(mean_reliday2, na.rm = T))
```

```{r retest_box_model}
# define data
mDataRetestBox <- reli %>% 
  filter(studyversion == "box" & sample == "kids") %>% 
  mutate(
    # scaled (centered around mean, SD = 1, i.e., z-transformed)
    age = scale(ageInMonths, center = TRUE, scale = TRUE)[,1], 
  ) %>% 
  select(subjID, age, reliday, correctBox)

# run model
mRetestBox <- brm(correctBox ~ age + (0 + reliday | subjID), 
                              data   = mDataRetestBox, 
                              family = bernoulli(link = "logit"),
                              warmup = 1000, 
                              iter   = 3000, 
                              chains = 4, 
                              inits  = "random",
                              cores  = 100)

write.csv(mRetestBox, "../saves/mRetestBox.csv", quote = F, row.names = F)
saveRDS(mRetestBox, "../saves/mRetestBox.rds")
```

```{r retest_box_kids}
box_retest_kids <- box_retest %>% 
  filter(sample == "kids") %>% 
  ggplot(., aes(x = mean_reliday1, y = mean_reliday2)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(aes(col = ageInYears), size = 0.7) + 
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d"), guide = "none") +
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 1, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  labs(x = "Testday 1", y = "Testday 2")

box_retest_kids

saveRDS(box_retest_kids, file = "../saves/tango-box-retest-kids.rds")
# ggsave("../figures/tango_box_retest_kids.png", width = 6, height = 4)
```

```{r retest_box_adults}
box_retest_adults <- box_retest %>% 
  filter(sample == "adults") %>% 
  ggplot(., aes(x = mean_reliday1, y = mean_reliday2)) + 
  geom_abline(intercept = 0, slope = 1, col = "darkgrey", linetype = "longdash") +
  geom_point(col = "darkgrey", size = 1.2, shape = 18, alpha = 0.5) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(method = "pearson", label.x = 0, label.y = 1, aes(label = paste(..r.label..)), size = 3.5, r.accuracy = 0.01, cor.coef.name = "r") + 
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  labs(x = "Testday 1", y = "Testday 2")

box_retest_adults

saveRDS(box_retest_adults, file = "../saves/tango-box-retest-adults.rds")
# ggsave("../figures/tango_hedge_retest_adults.png", width = 6, height = 4)
```

# Save plots

```{r arrange_plots}
# hedge_variation_plot_GLMM <- readRDS(file = "../saves/tango-hedge-variation-plot-GLMM.rds")
# hedge_intCon_kids <- readRDS(file = "../saves/tango-hedge-intCon-kids.rds")
# hedge_intCon_adults <- readRDS(file = "../saves/tango-hedge-intCon-adults.rds")
# hedge_retest_kids <- readRDS(file = "../saves/tango-hedge-retest-kids.rds")
# hedge_retest_adults <- readRDS(file = "../saves/tango-hedge-retest-adults.rds")
# box_variation_plot_GLMM <- readRDS(file = "../saves/tango-box-variation-plot-GLMM.rds")
# box_intCon_kids <- readRDS(file = "../saves/tango-box-intCon-kids.rds")
# box_intCon_adults <- readRDS(file = "../saves/tango-box-intCon-adults.rds")
# box_retest_kids <- readRDS(file = "../saves/tango-box-retest-kids.rds")
# box_retest_adults <- readRDS(file = "../saves/tango-box-retest-adults.rds")

tango_arrangedplot <- ggarrange(

  ggarrange(hedge_variation_plot_GLMM,
            NULL,
            ggarrange(
              hedge_intCon_kids, 
              hedge_intCon_adults,
              hedge_retest_kids, 
              hedge_retest_adults, 
              nrow = 2, 
              ncol = 2, 
              labels = c("B", "C", "D", "E")
            ), 
            
            # hedge: space between inddiff and reli
            nrow = 1, widths = c(1, 0.06, 1),
            labels = c("A", "", "")
  ), 
  
  NULL, 
  
  ggarrange(box_variation_plot_GLMM,
            NULL,
            ggarrange(
              box_intCon_kids,
              box_intCon_adults,
              box_retest_kids,
              box_retest_adults,
              nrow = 2, 
              ncol = 2,
              labels = c("G", "H", "I", "J")
            ), 
  
            # box: space between inddiff and reli
            nrow = 1, widths = c(1, 0.06, 1),
            labels = c("F", "", "")
  ), 
  
  # space between hedge & box
  nrow = 3, heights = c(1.2, 0.1, 1.2)
)

tango_arrangedplot
saveRDS(tango_arrangedplot, file = "../saves/tango-arrangedplot.rds")
ggsave("../figures/tango_arrangedplot.png", width = 6.5, height = 5, scale = 1.6, bg = "white")
```
