---
title: "supplements_webcamcoding"
author: "Julia Prein"
date: '2022-04-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(brms)
library(ggridges)
library(ggpubr)
library(tidybayes)

options(scipen = 999)
theme_set(theme_classic())
```

```{r load_data}
webcam_data <- readRDS(file = "../data/gafo-testtrials.rds") %>% 
  filter(studytype == "vali" & datacollection == "remote - unsupervised" & studyversion == "box" & webcam == TRUE & ageInYears == 3) %>% 
  group_by(subjID) %>% 
  # determine order of factors
  mutate(
    targetPosition = factor(targetPosition, levels = c("box1", "box2", "box3", "box4", "box5")), 
    proportionCorrectBox = mean(correctBox, na.rm = TRUE),
  )
```

### VISUAL EXPLORATION 

```{r webcam_exploring}
### nrRepeatedTestquestion
webcam_data %>% 
  group_by(subjID) %>% 
  mutate(repeatedTestquestion = mean(nrRepeatedTestquestion, na.rm = TRUE)) %>% 
  ggplot(., aes(x = repeatedTestquestion, y = proportionCorrectBox)) + 
  geom_point(col = "#006c66", size = 0.7) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(r.accuracy = 0.01, p.accuracy = 0.01) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))

### nrHintsEyes
webcam_data %>% 
  group_by(subjID) %>% 
  mutate(hintsEyes = mean(nrHintsEyes, na.rm = TRUE)) %>% 
  ggplot(., aes(x = hintsEyes, y = proportionCorrectBox)) + 
  geom_point(col = "#006c66", size = 0.7) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(r.accuracy = 0.01, p.accuracy = 0.01) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))

### nrVerificationChoice
webcam_data %>% 
  group_by(subjID) %>% 
  mutate(verificationChoice = mean(nrVerificationChoice, na.rm = TRUE)) %>% 
  ggplot(., aes(x = verificationChoice, y = proportionCorrectBox)) + 
  geom_point(col = "#006c66", size = 0.7) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(r.accuracy = 0.01, p.accuracy = 0.01) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))

### nrParentSpeech
webcam_data %>% 
  group_by(subjID) %>% 
  mutate(parentSpeech = mean(nrParentSpeech, na.rm = TRUE)) %>% 
  ggplot(., aes(x = parentSpeech, y = proportionCorrectBox)) + 
  geom_point(col = "#006c66", size = 0.7) + 
  geom_smooth(method = "lm", size = 0.5, alpha = 0.15, col = "darkgrey") +
  stat_cor(r.accuracy = 0.01, p.accuracy = 0.01) + 
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))
```

### MODELS ON TRIAL LEVEL

```{r webcam_perTrial_datapreparation}
# prepare data
mData <- webcam_data %>% 
  ungroup() %>% 
  mutate(
    correct = as.numeric(correctBox), 
    
    # centered around minimum
    age = ageInMonths - min(ageInMonths), 
    
    # centered around mean
    trial = scale(trialNr, center = TRUE, scale = FALSE), 
    repeatedTestquestion = scale(nrRepeatedTestquestion, center = TRUE, scale = FALSE),
    verificationChoice = scale(nrVerificationChoice, center = TRUE, scale = FALSE),
    hintsEyes = scale(nrHintsEyes, center = TRUE, scale = FALSE),
    nrParentSpeech = replace_na(nrParentSpeech, 0), 
    parentSpeech = scale(nrParentSpeech, center = TRUE, scale = FALSE),
    
    # calculating index
    parentalInterference = -(repeatedTestquestion) + -(verificationChoice) + hintsEyes, 
    
    # scaled (centered around mean, SD = 1, i.e., z-transformed)
    pi = scale(parentalInterference, scale = TRUE, center = TRUE), 
  ) %>% 
  select(trial, subjID, correct, targetPosition, age, parentalInterference, pi, repeatedTestquestion, verificationChoice, hintsEyes, parentSpeech)

```

```{r webcam_perTrial_models}
# originally: 
# brm(correct ~ age + (symmetricPosition | subjID) + (1 | targetPosition)
# age + person effect + trial effect
# simplified the model, since not a lot of data / info to estimate all the parameters. 
# therefore, remove trial & targetposition

mPerTrialNull <- brm(correct ~ age + (1 | subjID) + (1 | targetPosition), 
                              data   = mData, 
                              family = bernoulli(link = "logit"), 
                              warmup = 1000, 
                              iter   = 3000, 
                              chains = 4, 
                              inits  = "random",
                              cores  = 4)

# we decided to build an index since we're rather interested in the additive effect of the parameters; general parental inference
# we don't want to know what happens if we e.g. set repeatedQuestion & verfication to zero how does hintsEyes influence correct

# index: repeated testquestion & verification choice tend to lean into negative effect, 
# hints eyes rather positive. therefore -, - + for summing up
mPerTrialPI <- update(mPerTrialNull,
                      newdata = mData,
                      formula = correct ~ age + pi + (1 | subjID) + (1 | targetPosition), 
                      family = bernoulli(link = "logit"),
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerTrialRepeatedTestquestion <- update(mPerTrialNull,
                      newdata = mData,
                      formula = correct ~ age + repeatedTestquestion + (1 | subjID) + (1 | targetPosition), 
                      family = bernoulli(link = "logit"),
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerTrialVerificationChoice <- update(mPerTrialNull,
                      newdata = mData,
                      formula = correct ~ age + verificationChoice + (1 | subjID) + (1 | targetPosition), 
                      family = bernoulli(link = "logit"),
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerTrialHintsEyes <- update(mPerTrialNull,
                      newdata = mData,
                      formula = correct ~ age + hintsEyes + (1 | subjID) + (1 | targetPosition), 
                      family = bernoulli(link = "logit"),
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)


mPerTrialParentSpeech <- update(mPerTrialNull,
                      newdata = mData,
                      formula = correct ~ age + parentSpeech + (1 | subjID) + (1 | targetPosition), 
                      family = bernoulli(link = "logit"),
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)
```

```{r webcam_perTrial_comparisons}
mPerTrialNull <- add_criterion(mPerTrialNull, "waic")
mPerTrialPI <- add_criterion(mPerTrialPI, "waic")
mPerTrialRepeatedTestquestion <- add_criterion(mPerTrialRepeatedTestquestion, "waic")
mPerTrialVerificationChoice <- add_criterion(mPerTrialVerificationChoice, "waic")
mPerTrialHintsEyes <- add_criterion(mPerTrialHintsEyes, "waic")
mPerTrialParentSpeech <- add_criterion(mPerTrialParentSpeech, "waic")

mPerTrialComparison <- loo_compare(mPerTrialNull, mPerTrialPI, mPerTrialRepeatedTestquestion, mPerTrialVerificationChoice, mPerTrialHintsEyes, mPerTrialParentSpeech, criterion = "waic")

mPerTrialComparison <- as_tibble(mPerTrialComparison, rownames = "model")

mPerTrialComparisonWeights <- as_tibble(model_weights(mPerTrialNull, mPerTrialPI, mPerTrialRepeatedTestquestion, mPerTrialVerificationChoice, mPerTrialHintsEyes, mPerTrialParentSpeech, criterion = "waic"), rownames = "model")
```

```{r webcam_perTrial_posteriordraws}
perTrial_draws <- bind_rows(
  mPerTrialPI %>% gather_draws(b_pi),
  mPerTrialRepeatedTestquestion %>% gather_draws(b_repeatedTestquestion), 
  mPerTrialVerificationChoice %>% gather_draws(b_verificationChoice), 
  mPerTrialHintsEyes %>% gather_draws(b_hintsEyes), 
  mPerTrialParentSpeech %>% gather_draws(b_parentSpeech), 
  ) %>% 
  mutate(
    Predictor = factor(.variable, 
                       levels = c("b_verificationChoice", 
                                  "b_pi", 
                                  "b_repeatedTestquestion", 
                                  "b_parentSpeech", 
                                  "b_hintsEyes"
                       ), 
                       labels = c("# Verification choice", 
                                  "Parental interference index",
                                  "# Repeated testquestion", 
                                  "# Words uttered by caregiver", 
                                  "# Hints towards eyes"
                       )
                )  
  )

write.csv(perTrial_draws, "../saves/supplements-webcamcoding-perTrialdraws.csv", quote = F, row.names = F)
saveRDS(perTrial_draws, "../saves/supplements-webcamcoding-perTrialdraws.rds")
```

```{r webcam_perTrial_plot}
perTrial_plot <- perTrial_draws %>% 
  ggplot(., aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
 tidybayes::stat_halfeye(alpha = .8, .width = c(.95, .80)) +
    labs(x = "Posterior estimate", y = "") +
  guides(fill = "none")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_fill_manual(values = c("grey","#85AD00")) +
  scale_x_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 0.5)) +
  theme_minimal()

perTrial_plot

ggsave("../figures/supplements_webcamcoding_perTrial.png", width = 10, height = 6, scale = 0.7, bg = "white")
```

### MODELS ON SUBJECT LEVEL

```{r webcam_perSubject_datapreparation}
mDataSubj <- webcam_data %>% 
  group_by(subjID) %>% 
  mutate(
    trials = n(),
    correctTrials = sum(correctBox), 
    repeatedTestquestion = sum(nrRepeatedTestquestion), 
    verificationChoice = sum(nrVerificationChoice), 
    hintsEyes = sum(nrHintsEyes), 
    parentalInterference = -(repeatedTestquestion) + verificationChoice + -(hintsEyes),
    nrParentSpeech = replace_na(nrParentSpeech, 0), 
    parentSpeech = sum(nrParentSpeech), 
  ) %>% 
  slice(1) %>% 
  # for scaling we need ungrouped data!
  ungroup() %>% 
  mutate(
    age = ageInMonths - mean(ageInMonths), 
    pi = scale(parentalInterference, scale = TRUE, center = TRUE), 
  ) %>% 
  select(subjID, correctTrials, trials, age, repeatedTestquestion, verificationChoice, hintsEyes, parentSpeech, pi)
```

```{r webcam_perSubject_models}
mPerSubjectNull <- brm(correctTrials |  trials(trials) ~ age, 
                              data   = mDataSubj, 
                              family = binomial(link = "logit"), 
                              warmup = 1000, 
                              iter   = 3000, 
                              chains = 4, 
                              inits  = "random",
                              cores  = 4)

mPerSubjectPI <- update(mPerSubjectNull,
                      newdata = mDataSubj,
                      formula = correctTrials |  trials(trials) ~ age + pi, 
                      family = binomial(link = "logit"), 
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerSubjectRepeatedTestquestion <- update(mPerSubjectNull,
                      newdata = mDataSubj,
                      formula = correctTrials |  trials(trials) ~ age + repeatedTestquestion, 
                      family = binomial(link = "logit"), 
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerSubjectVerificationChoice <- update(mPerSubjectNull,
                      newdata = mDataSubj,
                      formula = correctTrials |  trials(trials) ~ age + verificationChoice, 
                      family = binomial(link = "logit"), 
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerSubjectHintsEyes <- update(mPerSubjectNull,
                      newdata = mDataSubj,
                      formula = correctTrials |  trials(trials) ~ age + hintsEyes, 
                      family = binomial(link = "logit"), 
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)

mPerSubjectParentSpeech <- update(mPerSubjectNull,
                      newdata = mDataSubj,
                      formula = correctTrials |  trials(trials) ~ age + parentSpeech, 
                      family = binomial(link = "logit"), 
                      warmup = 1000, 
                      iter   = 3000, 
                      chains = 4, 
                      inits  = "random",
                      cores  = 4)
```

```{r webcam_perSubject_comparisons}
mPerSubjectNull <- add_criterion(mPerSubjectNull, "waic")
mPerSubjectPI <- add_criterion(mPerSubjectPI, "waic")
mPerSubjectRepeatedTestquestion <- add_criterion(mPerSubjectRepeatedTestquestion, "waic")
mPerSubjectVerificationChoice <- add_criterion(mPerSubjectVerificationChoice, "waic")
mPerSubjectHintsEyes <- add_criterion(mPerSubjectHintsEyes, "waic")
mPerSubjectParentSpeech <- add_criterion(mPerSubjectParentSpeech, "waic")

mPerSubjectComparison <- loo_compare(mPerSubjectNull, mPerSubjectPI, mPerSubjectRepeatedTestquestion, mPerSubjectVerificationChoice, mPerSubjectHintsEyes, mPerSubjectParentSpeech, criterion = "waic")

mPerSubjectComparison <- as_tibble(mPerSubjectComparison, rownames = "model")

mPerSubjectComparisonWeights <- as_tibble(model_weights(mPerSubjectNull, mPerSubjectPI, mPerSubjectRepeatedTestquestion, mPerSubjectVerificationChoice, mPerSubjectHintsEyes, mPerSubjectParentSpeech, criterion = "waic"), rownames = "model")
```

```{r webcam_perSubject_posteriordraws}
perSubject_draws <- bind_rows(
  mPerSubjectPI %>% gather_draws(b_pi),
  mPerSubjectRepeatedTestquestion %>% gather_draws(b_repeatedTestquestion), 
  mPerSubjectVerificationChoice %>% gather_draws(b_verificationChoice), 
  mPerSubjectHintsEyes %>% gather_draws(b_hintsEyes), 
  mPerSubjectParentSpeech %>% gather_draws(b_parentSpeech), 
  ) %>% 
  mutate(
    Predictor = factor(.variable, 
                       levels = c("b_verificationChoice", 
                                  "b_pi", 
                                  "b_repeatedTestquestion", 
                                  "b_parentSpeech", 
                                  "b_hintsEyes"
                       ), 
                       labels = c("# Verification choice", 
                                  "Parental interference index",
                                  "# Repeated testquestion", 
                                  "# Words uttered by caregiver", 
                                  "# Hints towards eyes"
                       )
                )
  )

write.csv(perSubject_draws, "../saves/supplements-webcamcoding-perSubjectdraws.csv", quote = F, row.names = F)
saveRDS(perSubject_draws, "../saves/supplements-webcamcoding-perSubjectdraws.rds")
```

```{r webcam_perSubject_plot}
perSubject_plot <- perSubject_draws %>% 
  ggplot(., aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
 tidybayes::stat_halfeye(alpha = .8, .width = c(.95, .80), scale = 1.75) +
    labs(x = "Posterior estimate", y = "") +
  guides(fill = "none")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_fill_manual(values = c("grey","#85AD00")) +
  scale_x_continuous(limits = c(-1, 0.75), breaks = seq(-1, 0.75, 0.25)) +
  theme_minimal()

perSubject_plot

ggsave("../figures/supplements_webcamcoding_perSubject_draws.png", width = 10, height = 6, scale = 0.7, bg = "white")
```

```{r combined_plot}
ggarrange(perTrial_draws %>% 
            ggplot(., aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
            tidybayes::stat_halfeye(alpha = .8, .width = c(.95, .80)) +
            labs(x = "Posterior estimate", y = "") +
            guides(fill = "none")+
            geom_vline(xintercept = 0, linetype = "dashed") +
            scale_fill_manual(values = c("grey","#85AD00")) +
            scale_x_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
            theme_minimal() + 
            theme(panel.grid.minor.x = element_blank()), 
          
          ggarrange(
            perSubject_draws %>% 
              ggplot(., aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
              tidybayes::stat_halfeye(alpha = .8, .width = c(.95, .80), scale = 2) +
              labs(x = "", y = "") +
              guides(y = "none", fill = "none") +
              geom_vline(xintercept = 0, linetype = "dashed") +
              scale_fill_manual(values = c("grey","#85AD00")) +
              scale_x_continuous(limits = c(-1, 0.75), breaks = seq(-1, 0.75, 0.5)) +
              theme_minimal(), 
            NULL, 
            nrow = 2, heights = c(1, 0.0001)
          ), 
          
          nrow = 1, widths = c(1, 0.75),
          labels = c("A", "B")
          )

ggsave("../figures/supplements_webcamcoding_draws.png", width = 10, height = 6, scale = 0.7, bg = "white")
```

```{r overall_save}
overall_results <- bind_rows(mPerTrialComparison, mPerSubjectComparison) %>% 
  left_join(bind_rows(mPerTrialComparisonWeights, mPerSubjectComparisonWeights)) %>% 
  select(model, waic, se_waic, value, elpd_diff, se_diff) %>% 
  rename(
    Predictor = model, 
    WAIC = waic, 
    SE_WAIC = se_waic,
    Weight = value, 
    ELPD_DIFF = elpd_diff, 
    SE_ELPD_DIFF = se_diff,
  ) %>% 
  mutate(
    Predictor = recode(Predictor, 
                   "mPerTrialVerificationChoice" = "By trial - # Verification choice", 
                   "mPerTrialNull" = "By trial - Null model", 
                   "mPerTrialPI" = "By trial - Parental interference index", 
                   "mPerTrialRepeatedTestquestion" = "By trial - # Repeated testquestion", 
                   "mPerTrialParentSpeech" = "By trial - # Words uttered by caregiver", 
                   "mPerTrialHintsEyes" = "By trial - # Hints eyes", 
                   "mPerSubjectRepeatedTestquestion" = "By subject - # Repeated testquestion", 
                   "mPerSubjectPI" = "By subject - Parental interference index", 
                   "mPerSubjectNull" = "By subject - Null model", 
                   "mPerSubjectVerificationChoice" = "By subject - # Verification choice", 
                   "mPerSubjectParentSpeech" = "By subject - # Words uttered by caregiver", 
                   "mPerSubjectHintsEyes" = "By subject - # Hints eyes"
                   )
  )

overall_results

write.csv(overall_results, "../saves/supplements-webcamcoding-results.csv", quote = F, row.names = F)
saveRDS(overall_results, "../saves/supplements-webcamcoding-results.rds")
```

